# Use this YAML in your workflow file for each job

name: GitHub Actions Demo
run-name: is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: echo "🎉 The job was automatically triggered by a event."
